config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  #get 'home/index'
  get 'home/team'
  post "home/team" => 'home#team'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # common_content method is inherited only by :index and :team
  before_action :common_content, :only => [:index, :team]

  def common_content
    @hero_name = Faker::Superhero.name.titleize  
    @hero_power = Faker::Superhero.power.titleize 
    @coporate_power = Faker::Company.bs.titleize 
    @office_catchphrase = Faker::Marketing.buzzwords.titleize 
    @avatar = Faker::Avatar.image(slug: @random, size: "500x500", format: "png", set: @set, bgset: @background)
    
    @bg = rand(1..2)
    @random = rand(1..1000)
    @set_number = rand(1..4)
    #Randomly pick avatarimage
    if @set_number == 1
      @set = "set1"
    elsif @set_number == 2
      @set = "set2"
    elsif @set_number == 3
      @set = "set3"
    else
      @set = "set4"
    end
    #Randomly pick bg image
    if @bg == 1
      @background = "bg1"
    else
      @background = "bg2"
    end

    @avatar = Faker::Avatar.image(slug: @random, size: "300x300", format: "png", set: @set, bgset: @background)


  end

  def index
  end

  def team
    @team_number = params[:team_number].to_i

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">

    <%= form_tag home_team_path, :method => 'POST' do %>
      <%= select_tag(:team_number, options_for_select([
                  ['1', 1],
                  ['2', 2],
                  ['3', 3],
                  ['4', 4],
                  ['5', 5],
                  ['6', 6],
                  ['7', 7],
                  ['8', 8],
                  ['9', 9],
                  ['10', 10]
                  ]), class: 'form-control') %>    

    <%= submit_tag 'Build Your Team!', class:"btn btn-success" %>
    <%end%>
  </div>
</div> 

app/views/home/_navbar.html.erb
<% link_to 'Home', root_path %>
<% link_to 'Create a team', home_team_path %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
     <%= link_to 'Superhero Generator', root_path, class: "navbar-brand" %> 
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item col-5 mx-auto">
        <%= link_to 'Create a new superhero', root_path, class: "nav-link", class: "btn btn-info" %> 
        </li> 
        <li class="nav-item col-5 mx-auto">
        <%= link_to 'Create a team of superheroes ', home_team_path, class: "nav-link", class: "btn btn-info " %> 
        </li>
        
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/_show_team.html.erb
<% @team_number.times do %>

  <% @bg = rand(1..2) %> 
  <% @random = rand(1..1000) %>
  <%  @set_number = rand(1..4) %>
  
  <%  if @set_number == 1 %>
    <%  @set = "set1" %>
    <% elsif @set_number == 2 %>
    <%   @set = "set2" %>
    <% elsif @set_number == 3 %>
      <% @set = "set3" %>
    <% else %>
      <% @set = "set4" %>
    <% end %>
    
    <% if @bg == 1 %>
      <% @background = "bg1" %>
    <% else %>
      <% @background = "bg2" %>
    <% end %>

    <% @avatar = Faker::Avatar.image(slug: @random, size: "300x300", format: "png", set: @set, bgset: @background) %>
    
  <div class="container-fluid">
  <img src="<%= @avatar %>"
    /div>

    <div class="container-fluid">
    <h4>Your Superhero Name: <span> <%= Faker::Superhero.name.titleize %></span> </h4>
    </div>
    <br/>
    <div class="container-fluid">
    <h4>Your Superpower: <span> <%= Faker::Superhero.power.titleize %> </span> </h4>
    </div>
    <br/>
    <div class="container-fluid">
    <h5>Your Catchphrase Is: <span><%= Faker::Marketing.buzzwords.titleize %> </span>
    </h5>
    </div>
    <br/>
    <div class="container-fluid">
    <h5>Your Corporate Superpower Is: <span><%= Faker::Company.bs.titleize %> </span></h5>
    </div>
    <br/>
    <div class="container-fluid">
    <a><%= link_to 'Generate another superhero', root_path, class:"btn btn-primary" %> </a>
  </div>
  
</div> 

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/team.html.erb
<br/>

<div class="container-fluid">
    <a class="btn btn-primary btn-lg"><% if @team_number > 0 %> Your Superhero Team: 
      ><% else %>                               How many members in your team? <% end %></a>


    <% if @team_number > 0 %>
     <%= render 'home/show_team' %> 
    <% else %>
      <%= render 'home/create_team' %> 
    <% end %>
        
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superhero Generator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>


  <div class="container-fluid">
    <%= yield %>
  </div>

    <center>Copyright © Jordan Fox - All Rights Reserved</center>

  </body>
</html>